In [8]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn import linear_model
from sklearn import preprocessing
from sklearn import utils
from sklearn import ensemble
import xgboost as xgb
import lightgbm as lgb




test_data=pd.read_csv('Test.csv',na_values=" ")
training_data = pd.read_csv('Train.csv',na_values=' ')

dict={'Employee_ID':test_data['Employee_ID']}
print(training_data.dtypes)
print(test_data.dtypes)


Employee_ID                   object
Gender                        object
Age                          float64
Education_Level                int64
Relationship_Status           object
Hometown                      object
Unit                          object
Decision_skill_possess        object
Time_of_service              float64
Time_since_promotion           int64
growth_rate                    int64
Travel_Rate                    int64
Post_Level                     int64
Pay_Scale                    float64
Compensation_and_Benefits     object
Work_Life_balance            float64
VAR1                           int64
VAR2                         float64
VAR3                         float64
VAR4                         float64
VAR5                           int64
VAR6                           int64
VAR7                           int64
Attrition_rate               float64
dtype: object
Employee_ID                   object
Gender                        object
Age                     

In [9]:
training_data['Gender'] = training_data.Gender.map({'F': 0, 'M': 1})
test_data['Gender'] = test_data.Gender.map({'F': 0, 'M': 1})

training_data['Relationship_Status'] = training_data.Relationship_Status.map({'Single':0,'Married':1})
test_data['Relationship_Status'] = test_data.Relationship_Status.map({'Single':0,'Married':1})

freq_encode=training_data.groupby('Hometown').size()/100
training_data.loc[:,'Hometown']=training_data['Hometown'].map(freq_encode)
test_data.loc[:,'Hometown']=test_data['Hometown'].map(freq_encode)

mean_encode=training_data.groupby('Unit')['Attrition_rate'].mean()
training_data.loc[:,'Unit']=training_data['Unit'].map(mean_encode)
test_data.loc[:,'Unit']=test_data['Unit'].map(mean_encode)

#print(training_data.Decision_skill_possess.value_counts())
training_data['Decision_skill_possess'] = training_data.Decision_skill_possess.map({'Conceptual':0,'Analytical':1,'Directive':2,'Behavioral':3})
test_data['Decision_skill_possess'] = test_data.Decision_skill_possess.map({'Conceptual':0,'Analytical':1,'Directive':2,'Behavioral':3})

mean_encode=training_data.groupby('Compensation_and_Benefits')['Attrition_rate'].mean()
training_data.loc[:,'Compensation_and_Benefits']=training_data['Compensation_and_Benefits'].map(mean_encode)
test_data.loc[:,'Compensation_and_Benefits']=test_data['Compensation_and_Benefits'].map(mean_encode)

print(training_data.dtypes)
print(test_data.dtypes)

print(training_data.isnull().sum())
print(test_data.isnull().sum())

Employee_ID                   object
Gender                         int64
Age                          float64
Education_Level                int64
Relationship_Status            int64
Hometown                     float64
Unit                         float64
Decision_skill_possess         int64
Time_of_service              float64
Time_since_promotion           int64
growth_rate                    int64
Travel_Rate                    int64
Post_Level                     int64
Pay_Scale                    float64
Compensation_and_Benefits    float64
Work_Life_balance            float64
VAR1                           int64
VAR2                         float64
VAR3                         float64
VAR4                         float64
VAR5                           int64
VAR6                           int64
VAR7                           int64
Attrition_rate               float64
dtype: object
Employee_ID                   object
Gender                         int64
Age                     

In [10]:
training_data['Age']=training_data['Age'].fillna(training_data['Age'].mean())
test_data['Age']=test_data['Age'].fillna(test_data['Age'].mean())

training_data['Time_of_service']=training_data['Time_of_service'].fillna(0)
test_data['Time_of_service']=test_data['Time_of_service'].fillna(0)

training_data['Pay_Scale']=training_data['Pay_Scale'].fillna(training_data['Pay_Scale'].mean())
test_data['Pay_Scale']=test_data['Pay_Scale'].fillna(test_data['Pay_Scale'].mean())

training_data['Work_Life_balance']=training_data['Work_Life_balance'].fillna(training_data['Work_Life_balance'].mean())
test_data['Work_Life_balance']=test_data['Work_Life_balance'].fillna(test_data['Work_Life_balance'].mean())

training_data['VAR2']=training_data['VAR2'].fillna(training_data['VAR2'].mean())
test_data['VAR2']=test_data['VAR2'].fillna(test_data['VAR2'].mean())

training_data['VAR4']=training_data['VAR4'].fillna(training_data['VAR4'].mean())
test_data['VAR4']=test_data['VAR4'].fillna(test_data['VAR4'].mean())

print(training_data.isnull().sum())
print(test_data.isnull().sum())

Employee_ID                  0
Gender                       0
Age                          0
Education_Level              0
Relationship_Status          0
Hometown                     0
Unit                         0
Decision_skill_possess       0
Time_of_service              0
Time_since_promotion         0
growth_rate                  0
Travel_Rate                  0
Post_Level                   0
Pay_Scale                    0
Compensation_and_Benefits    0
Work_Life_balance            0
VAR1                         0
VAR2                         0
VAR3                         0
VAR4                         0
VAR5                         0
VAR6                         0
VAR7                         0
Attrition_rate               0
dtype: int64
Employee_ID                  0
Gender                       0
Age                          0
Education_Level              0
Relationship_Status          0
Hometown                     0
Unit                         0
Decision_skill_possess    

In [11]:
X_train = training_data.iloc[:, 1:-1].values
y_train = training_data.iloc[:, -1].values
print(X_train)
print(y_train)
#X_train=preprocessing.normalize(X_train)


test_data = test_data.iloc[:, 1:].values
#test_data=preprocessing.normalize(test_data)

[[ 0. 42.  4. ...  4.  5.  3.]
 [ 1. 24.  3. ...  3.  5.  3.]
 [ 0. 58.  3. ...  3.  8.  3.]
 ...
 [ 0. 49.  3. ...  4.  8.  3.]
 [ 0. 47.  3. ...  3.  6.  3.]
 [ 0. 58.  3. ...  4.  5.  3.]]
[0.1841 0.067  0.0851 ... 0.7847 0.4162 0.091 ]


In [14]:
clf=linear_model.Lasso(alpha=0.01)
#clf=ensemble.GradientBoostingRegressor(n_estimators=100,learning_rate=0.01,max_depth=1,random_state=0)
#clf=linear_model.LinearRegression()
#clf=linear_model.TheilSenRegressor()

#clf=ensemble.BaggingRegressor()
#clf=ensemble.RidgeRegressor()
#clf=ensemble.RandomForestRegressor()
#clf=ensemble.ExtraTreesRegressor()
#clf=ensemble.AdaBoostRegressor()

#clf=svm.SVR(kernel='rbf')

#clf=linear_model.SGDRegressor()
#clf=linear_model.BayesianRidge()
#clf=linear_model.ElasticNet()
#clf=linear_model.PassiveAggressiveRegressor()

#clf =xgb.XGBRegressor(objective='reg:linear',colsample_bytree=0.3,learning_rate=0.1,max_depth=5,alpha=10,n_estimators=10)

'''
d_train=lgb.Dataset(X_train,label=y_train)
params={}
params['learning_rate']=0.00000001
params['boosting']='gbdt'
params['bagging_freq']=1
params['bagging_fraction']=0.4
params['max_depth']=-1
decision=lgb.train(params,d_train,100)
'''


decision=clf.fit(X_train,y_train)
prediction=decision.predict(test_data)
print(prediction)

[0.18880766 0.18526342 0.18452463 ... 0.18644764 0.18463651 0.19257032]


In [16]:
dict.update({'Attrition_rate':prediction})
target_data=pd.DataFrame(dict)
print(target_data)

target_data.to_csv('target_xg.csv', index=False)


     Employee_ID  Attrition_rate
0      EID_22713        0.188808
1       EID_9658        0.185263
2      EID_22203        0.184525
3       EID_7652        0.187512
4       EID_6516        0.189657
...          ...             ...
2995   EID_22547        0.190864
2996   EID_10066        0.191445
2997    EID_7126        0.186448
2998    EID_4929        0.184637
2999   EID_24750        0.192570

[3000 rows x 2 columns]
